FROM node:20-alpine as builder

WORKDIR /app

COPY package.json package-lock.json* ./
COPY packages/ ./packages/
COPY apps/dashboard/ ./apps/dashboard/

RUN npm install --workspace=apps/dashboard --workspace=packages/types --workspace=packages/ui
RUN npm run --workspace=apps/dashboard build

FROM node:20-alpine as runner

WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder /app/apps/dashboard/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/apps/dashboard/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/dashboard/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
