import type { MemoryItem } from "@nexus/types";

export const mockMemories: MemoryItem[] = [
  {
    id: "mem_sem_001",
    memory_class: "semantic",
    title: "Project Technology Stack Preferences",
    content: "Prefers TypeScript with strict types for frontends, Python FastAPI with Pydantic v2 for backends. Disapproves of unstructured mock data.",
    confidence: 0.98,
    enabled: true,
    tags: ["architecture", "preferences", "standards"],
    created_at: "2026-09-18 10:00:00",
    updated_at: "2026-09-18 10:00:00",
  },
  {
    id: "mem_proc_002",
    memory_class: "procedural",
    title: "Alembic Migration Recipe",
    content: "When applying migrations locally, run 'alembic -c infra/database/alembic.ini upgrade head'. Ensure virtualenv has greenlet and aiosqlite installed.",
    confidence: 0.95,
    enabled: true,
    tags: ["database", "migrations", "workflow"],
    created_at: "2026-09-18 12:15:00",
    updated_at: "2026-09-18 12:15:00",
  },
  {
    id: "mem_episodic_003",
    memory_class: "episodic",
    title: "Phase 1 Monorepo Bootstrap Success",
    content: "Successfully initialized monorepo workspaces, set up FastAPI health router, applied initial database schema with 7 tables, and established GitHub Actions CI pipeline.",
    confidence: 1.0,
    source_turn_id: "turn_sess_01H9A2M9002_14",
    enabled: true,
    tags: ["history", "phase1", "milestone"],
    created_at: "2026-09-18 18:00:00",
    updated_at: "2026-09-18 18:00:00",
  },
  {
    id: "mem_conv_004",
    memory_class: "conversational",
    title: "User Design Direction Directives",
    content: "Visual direction requested: Premium, minimal, technical, intelligent, calm, modern, NOT a generic SaaS template.",
    confidence: 1.0,
    source_turn_id: "turn_sess_01H9A1K4001_1",
    enabled: true,
    tags: ["ui", "design", "user-directive"],
    created_at: "2026-09-18 19:02:00",
    updated_at: "2026-09-18 19:02:00",
  },
  {
    id: "mem_work_005",
    memory_class: "working",
    title: "Active Working Directory Context",
    content: "Current project root: /Users/apple/coding/nexus. Database fallback active on SQLite WAL at .nexus/nexus.db.",
    confidence: 1.0,
    enabled: true,
    tags: ["scratchpad", "context", "active"],
    created_at: "2026-09-18 19:03:00",
    updated_at: "2026-09-18 19:03:00",
  },
];
