import type { AuditEvent } from "@nexus/types";

export const mockAuditLogs: AuditEvent[] = [
  {
    event_id: "evt_1001_snap",
    timestamp: "2026-09-18 18:31:05",
    session_id: "sess_01H9A1K4001",
    step_id: "step_1",
    agent_name: "CodingAgent",
    tool_name: "filesystem.read",
    action_type: "READ",
    risk_level: "LOW",
    inputs: { file_path: "services/api/nexus_api/middleware.py" },
    policy_decision: "auto_approved",
    execution_duration_ms: 1.45,
    undo_registered: false,
  },
  {
    event_id: "evt_1002_snap",
    timestamp: "2026-09-18 17:45:30",
    session_id: "sess_01H9A2M9002",
    step_id: "step_11",
    agent_name: "SystemOperatorAgent",
    tool_name: "terminal.execute",
    action_type: "EXECUTE",
    risk_level: "MEDIUM",
    inputs: { command: "alembic -c infra/database/alembic.ini upgrade head" },
    outputs: { exit_code: 0, stdout: "Running upgrade -> 001_initial_schema" },
    policy_decision: "approved_by_user",
    execution_duration_ms: 320.12,
    undo_registered: true,
  },
  {
    event_id: "evt_1003_snap",
    timestamp: "2026-09-18 17:40:12",
    session_id: "sess_01H9A2M9002",
    agent_name: "CodingAgent",
    tool_name: "filesystem.modify",
    action_type: "MODIFY",
    risk_level: "MEDIUM",
    inputs: { file_path: "infra/database/env.py" },
    snapshot_id: "snap_99a81c002",
    policy_decision: "approved_by_user",
    execution_duration_ms: 12.8,
    undo_registered: true,
  },
  {
    event_id: "evt_1004_snap",
    timestamp: "2026-09-18 15:20:00",
    session_id: "sess_01H9A4P2004",
    agent_name: "SystemOperatorAgent",
    tool_name: "filesystem.delete",
    action_type: "DELETE",
    risk_level: "HIGH",
    inputs: { file_path: "tests/scratch_test.tmp" },
    snapshot_id: "snap_44c11b889",
    policy_decision: "approved_by_user",
    execution_duration_ms: 4.1,
    undo_registered: true,
    undone_at: "2026-09-18 15:22:10",
  },
  {
    event_id: "evt_1005_snap",
    timestamp: "2026-09-18 14:10:45",
    session_id: "sess_01H9A4P2004",
    agent_name: "CodingAgent",
    tool_name: "terminal.execute",
    action_type: "EXECUTE",
    risk_level: "CRITICAL",
    inputs: { command: "rm -rf /etc/hosts" },
    error: "PolicyViolationError: Command blocked by PolicyEngine (Action classified as CRITICAL/FORBIDDEN)",
    policy_decision: "blocked_by_policy",
    execution_duration_ms: 0.25,
    undo_registered: false,
  },
];
