import type { ToolManifest } from "@nexus/types";

export const mockTools: ToolManifest[] = [
  {
    name: "filesystem.read",
    description: "Read file contents or list directory entries within allowed workspace boundaries.",
    action_type: "READ",
    risk_level: "LOW",
    input_schema: { file_path: "string", offset: "number?", limit: "number?" },
    output_schema: { content: "string", total_lines: "number" },
    reversibility: false,
    audit_required: true,
  },
  {
    name: "filesystem.write",
    description: "Create a new file with specified content. Reversible by automatic deletion upon rollback.",
    action_type: "WRITE",
    risk_level: "MEDIUM",
    input_schema: { file_path: "string", content: "string" },
    output_schema: { bytes_written: "number", sha256: "string" },
    reversibility: true,
    audit_required: true,
  },
  {
    name: "filesystem.modify",
    description: "Modify an existing file using a unified diff or whole replacement. Captured by snapshot vault before mutation.",
    action_type: "MODIFY",
    risk_level: "MEDIUM",
    input_schema: { file_path: "string", patch: "string" },
    output_schema: { lines_changed: "number", snapshot_id: "string" },
    reversibility: true,
    audit_required: true,
  },
  {
    name: "filesystem.delete",
    description: "Delete an existing file or directory. Pre-execution snapshot taken before deletion.",
    action_type: "DELETE",
    risk_level: "HIGH",
    input_schema: { file_path: "string" },
    output_schema: { status: "deleted", snapshot_id: "string" },
    reversibility: true,
    audit_required: true,
  },
  {
    name: "terminal.execute",
    description: "Execute a command in a sandboxed shell process with strict path containment and timeout limits.",
    action_type: "EXECUTE",
    risk_level: "HIGH",
    input_schema: { command: "string", cwd: "string?", timeout_seconds: "number?" },
    output_schema: { exit_code: "number", stdout: "string", stderr: "string" },
    reversibility: false,
    audit_required: true,
  },
  {
    name: "browser.open",
    description: "Navigate to a URL using Playwright headless browser instance.",
    action_type: "EXTERNAL_ACTION",
    risk_level: "MEDIUM",
    input_schema: { url: "string" },
    output_schema: { title: "string", status_code: "number" },
    reversibility: false,
    audit_required: true,
  },
  {
    name: "browser.search",
    description: "Perform web search query and retrieve ranked search snippets.",
    action_type: "READ",
    risk_level: "LOW",
    input_schema: { query: "string", limit: "number?" },
    output_schema: { results: "array" },
    reversibility: false,
    audit_required: true,
  },
];
